sonar.projectKey=memorias975-backend
sonar.projectName=memorias975-backend
sonar.sources=backend
sonar.tests=backend/tests
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.venv/**,**/venv/**