DROP TABLE IF EXISTS interactions;
CREATE TABLE interactions (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_email VARCHAR(255),
    session_id VARCHAR(255),
    ip_address VARCHAR(64),
    query TEXT,
    model_name_relevance VARCHAR(128),
    model_name_synthesis VARCHAR(128),
    relevance_filtered_collections TEXT,
    relevance_filtered_collections_flag INT,
    relevance_filtered_documents TEXT,
    relevance_filtered_documents_flag INT,
    graph_feedback INT,
    graph_feedback_comment TEXT,
    relevance_analysis JSONB,
    relevance_chunks_used INT,
    synthesis TEXT,
    synthesis_length_words INT,
    synthesis_length_chars INT,
    synthesis_feedback INT,
    synthesis_feedback_comment TEXT,
    rating INT,
    comment TEXT,
    contar INT DEFAULT 1,
    feedback_type VARCHAR(64),
    source VARCHAR(64),
    client_version VARCHAR(64),
    UNIQUE(user_email, session_id, query)
);
