name: Check Branch Flow

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  check-source: # Este nombre debe coincidir con el 'context' en tus Rulesets
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch source
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          TARGET_BRANCH="${{ github.base_ref }}"

          echo "Evaluando flujo: $SOURCE_BRANCH -> $TARGET_BRANCH"

          # REGLA 1: Solo develop -> main
          if [ "$TARGET_BRANCH" = "main" ] && [ "$SOURCE_BRANCH" != "develop" ]; then
            echo "::error::Flujo inválido. Solo se permite merge a 'main' desde 'develop'."
            exit 1
          fi

          # REGLA 2: Solo feature/* -> develop
          if [ "$TARGET_BRANCH" = "develop" ]; then
            if [[ ! "$SOURCE_BRANCH" =~ ^feature/ ]]; then
              echo "::error::Flujo inválido. Solo se permiten merges a 'develop' desde ramas 'feature/*'."
              exit 1
            fi
          fi

          echo "Flujo de ramas válido." 
          